require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.autopairs"
spec "user.autotag"
spec "user.bufdelete"
spec "user.colorscheme"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.illuminate"
spec "user.gitsigns"
spec "user.whichkey"
-- spec "user.nvimtree"
spec "user.indentline"
spec "user.neotree"
spec "user.comment"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.neotest"
spec "user.lazygit"
spec "user.project"
spec "user.conform"
spec "user.lint"
spec "user.dap"
spec "user.image"
spec "user.extras.bqf"
spec "user.miniicons"
-- spec "user.multicursors"
-- spec "user.extras.vim_test"
spec "user.extras.fidget"
spec "user.extras.tmux"
spec "user.extras.neoscroll"
spec "user.extras.copilot"
spec "user.extras.colorizer"
spec "user.extras.gitlinker"
spec "user.extras.eyeliner"
spec "user.extras.gopher"
spec "user.extras.venv_selector"
spec "user.extras.rustaceanvim"
spec "user.extras.neotab"

require "user.lazy"
